export const INPUT_FOCUS = 'header/input_focus'
export const INPUT_BLUR = 'header/input_blur'
export const CHANGE_LIST = 'header/change_list'
export const MOUSE_IN = 'header/MOUSE_IN'
export const MOUSE_OUT = 'header/MOUSE_OUT'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'